# Generated by Django 4.1 on 2022-08-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
