# Generated by Django 4.1 on 2022-08-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_item_price_item_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
